# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_auto_20190324_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nhood',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
