# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20190325_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhoodname',
            field=models.TextField(blank=True),
        ),
    ]
