# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(choices=[('Langata', 'Langata'), ('South-B', 'South-B'), ('Woodley', 'Woodley'), ('Kiambu', 'Kiambu')], max_length=50),
        ),
    ]
