# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0008_auto_20190325_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.TextField(),
        ),
    ]
