# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0009_auto_20190325_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhoodname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
        ),
    ]
